Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> Failure is due to "AttributeError: 'PlaybookCLI' object has no attribute 'base_parser'" in lib/python2.7/site-packages/testinfra/utils/ansible_runner.py 
> 
> Maybe a mismatch of dependency versions pulled by molecule?

I don't really know. I do know that I can't get the molecule tests to run for me locally. It fails on the container setup for some reason. Not certain why there since it states it was done with no log enabled :(

Patch-set: 1
Reviewer: Gerrit User 1 <1@f2a2391d-0403-4fa5-b183-4056999a8a09>
Label: Code-Review=0