Update patch set 1
Patch Set 1:

Failure is due to "AttributeError: 'PlaybookCLI' object has no attribute 'base_parser'" in lib/python2.7/site-packages/testinfra/utils/ansible_runner.py 

Maybe a mismatch of dependency versions pulled by molecule?

Patch-set: 1
Label: Verified=0